name = "Robusthera"
license = "MIT"
licenselink = "https://github.com/dim0627/hugo_theme_robust/blob/master/LICENSE.md"
description = "A fork of robust"
tags = ["blog"]
features = ["blog"]
min_version = 0.15


[author]
    name = "Bera"
    homepage = "http://github.com/ahmedbera/"
